
D2L.DragDrop.DragDropInfo=D2L.Class.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.OnDragDropped="";this.OnDragEnter="";this.OnDragExit="";this.OnDragOver="";this.OnDrop="";this.OnEndDrag="";this.OnEnter="";this.OnExit="";this.OnMouseDown="";this.OnOver="";this.OnStartDrag="";this.OnMouseOver="";this.OnMouseOut="";this.ScrollsPage=true;this.CustomGhostRenderer="";this.CustomInteractionValidator="";this.m_data=new D2L.Util.Dictionary},DeserializeMin:function(deserializer){this.OnDragDropped=
deserializer.GetMember();this.OnDragEnter=deserializer.GetMember();this.OnDragExit=deserializer.GetMember();this.OnDragOver=deserializer.GetMember();this.OnDrop=deserializer.GetMember();this.OnEndDrag=deserializer.GetMember();this.OnEnter=deserializer.GetMember();this.OnExit=deserializer.GetMember();this.OnMouseDown=deserializer.GetMember();this.OnOver=deserializer.GetMember();this.OnStartDrag=deserializer.GetMember();this.OnMouseOver=deserializer.GetMember();this.OnMouseOut=deserializer.GetMember();
this.ScrollsPage=deserializer.GetBoolean();this.CustomGhostRenderer=deserializer.GetMember();this.CustomInteractionValidator=deserializer.GetMember();this.m_data=deserializer.GetObject(D2L.Util.Dictionary)},SetData:function(key,value){this.m_data.Add(key,value)}});
D2L.Control.DragDropSettings=D2L.Control.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_dragDropInfo},IntegrateControlMin:function(deserializer){arguments.callee.$.IntegrateControlMin.call(this,deserializer);this.m_dragDropInfo=deserializer.GetObjectMin(D2L.DragDrop.DragDropInfo)},GetDragDropInfo:function(){return this.m_dragDropInfo}});
D2L.DragDrop.SetDragDropInfo=function(ddObject,ddInfo){var me=this;if(ddInfo.OnDragDropped)ddObject.OnDragDropped.RegisterMethod(function(ddArg){ddInfo.OnDragDropped(ddObject,ddArg)});if(ddInfo.OnDragEnter)ddObject.OnDragEnter.RegisterMethod(function(ddArg){ddInfo.OnDragEnter(ddObject,ddArg)});if(ddInfo.OnDragExit)ddObject.OnDragExit.RegisterMethod(function(ddArg){ddInfo.OnDragExit(ddObject,ddArg)});if(ddInfo.OnDragOver)ddObject.OnDragOver.RegisterMethod(function(ddArg,evt){ddInfo.OnDragOver(ddObject,
ddArg,evt)});if(ddInfo.OnDrop)ddObject.OnDrop.RegisterMethod(function(ddArg,evt){ddInfo.OnDrop(ddObject,ddArg,evt)});if(ddInfo.OnEndDrag)ddObject.OnEndDrag.RegisterMethod(function(){ddInfo.OnEndDrag(ddObject)});if(ddInfo.OnEnter)ddObject.OnEnter.RegisterMethod(function(ddArg){ddInfo.OnEnter(ddObject,ddArg)});if(ddInfo.OnExit)ddObject.OnExit.RegisterMethod(function(ddArg){ddInfo.OnExit(ddObject,ddArg)});if(ddInfo.OnMouseDown)ddObject.OnMouseDown.RegisterMethod(function(){ddInfo.OnMouseDown(ddObject)});
if(ddInfo.OnOver)ddObject.OnOver.RegisterMethod(function(ddArg,evt){ddInfo.OnOver(ddObject,ddArg,evt)});if(ddInfo.OnStartDrag)ddObject.OnStartDrag.RegisterMethod(function(){ddInfo.OnStartDrag(ddObject)});if(ddInfo.OnMouseOver)ddObject.OnMouseOver.RegisterMethod(function(){ddInfo.OnMouseOver(ddObject)});if(ddInfo.OnMouseOut)ddObject.OnMouseOut.RegisterMethod(function(){ddInfo.OnMouseOut(ddObject)});ddObject.SetScroll(ddInfo.ScrollsPage);if(ddInfo.CustomGhostRenderer)ddObject.SetCustomGhostRenderer(ddInfo.CustomGhostRenderer);
if(ddInfo.CustomInteractionValidator){var customInteractionValidatorFunc=ddInfo.CustomInteractionValidator;var customInteractionValidatorHandler=function(dd,isOver){if(isOver)return customInteractionValidatorFunc(dd,ddObject);else return customInteractionValidatorFunc(ddObject,dd)};ddObject.SetCustomInteractionValidatorHandler(customInteractionValidatorHandler)}for(var i=0;i<ddInfo.m_data.Keys().length;i++){var dicKey=ddInfo.m_data.Keys()[i];ddObject.SetData(dicKey,ddInfo.m_data.Get(dicKey))}};
D2L.DragDrop.Manager=D2L.Class.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_customProxy=null;this.m_dragdrops=new D2L.Util.Dictionary},GetCustomProxy:function(){if(this.m_customProxy==null){var d2lBody=UI.GetById("d2l_body");this.m_customProxy=UI.CreateElement("div");this.m_customProxy.id=UI.GetUniqueHtmlId();this.m_customProxy.style.position="absolute";this.m_customProxy.style.height="0px";this.m_customProxy.style.width="0px";this.m_customProxy.style.overflow="hidden";
d2lBody.appendChild(this.m_customProxy)}return this.m_customProxy},GetDragDrop:function(id){return this.m_dragdrops.Get(id)},RegisterDragDrop:function(id,dd){this.m_dragdrops.Add(id,dd)},RefreshCache:function(){YAHOO.util.DragDropMgr.refreshCache()}});
D2L.DragDrop.DraggableDroppable=D2L.Class.extend({Construct:function(control,domNode,group,mode){arguments.callee.$.Construct.call(this);if(D2L.Util.Html.IsDomNode(control)){var d2lcontrol=new D2L.Control;d2lcontrol.IDomNode=control;d2lcontrol.m_hasDomBeenBuilt=true;control=d2lcontrol}if(domNode===undefined||domNode===null)domNode=control.GetDomNode();if(mode===undefined||mode===null)mode=D2L.DragDrop.Modes.DraggableDroppable;if(group===undefined||group===null)group="D2L.DragDrop.DefaultGroup";this.m_control=
control;this.m_customGhostRenderer=null;this.m_customGhostControl=null;this.m_customInteractionValidatorHandler=null;this.m_cursorDrag="default";this.m_cursorInvalid="default";this.m_data=new D2L.Util.Dictionary;this.m_domNode=domNode;this.m_ghost=null;this.m_ghostOpacity=0.5;this.m_group=group;this.m_isValid=false;this.m_scroll=true;this.m_mode=mode;this.m_yuiDDObject=null;this.OnMouseDown=new D2L.EventHandler;this.OnStartDrag=new D2L.EventHandler;this.OnEndDrag=new D2L.EventHandler;this.OnDrop=
new D2L.EventHandler;this.OnDragDropped=new D2L.EventHandler;this.OnOver=new D2L.EventHandler;this.OnDragOver=new D2L.EventHandler;this.OnEnter=new D2L.EventHandler;this.OnDragEnter=new D2L.EventHandler;this.OnExit=new D2L.EventHandler;this.OnDragExit=new D2L.EventHandler;this.OnMouseOver=new D2L.EventHandler;this.OnMouseOut=new D2L.EventHandler;this.InstallDragDrop()},AddToGroup:function(group){this.m_yuiDDObject.addToGroup(group)},GetControl:function(){return this.m_control},GetCustomGhostControl:function(){return this.m_customGhostControl},
GetData:function(key){return this.m_data.Get(key)},GetDropIsValid:function(){return this.m_isValid},GetGhost:function(){return this.m_ghost},GetGhostOpacity:function(){return this.m_ghostOpacity},GetMode:function(){return this.m_mode},InstallDragDrop:function(){var me=this;if(this.m_domNode.id=="")this.m_domNode.id=UI.GetUniqueHtmlId();if(this.GetMode()==D2L.DragDrop.Modes.Droppable)this.m_yuiDDObject=new YAHOO.util.DDTarget(this.m_domNode.id,this.m_group);else{this.m_domNode.style.cursor=this.m_cursorDrag;
var customProxy=D2L.DragDrop.GetManager().GetCustomProxy();this.m_yuiDDObject=new YAHOO.util.DDProxy(this.m_domNode.id,this.m_group,{dragElId:customProxy.id})}this.m_yuiDDObject.scroll=this.m_scroll;D2L.DragDrop.GetManager().RegisterDragDrop(this.m_domNode.id,this);var onMouseOverFunc=function(e){me.OnMouseOver.Trigger()};var onMouseOutFunc=function(e){me.OnMouseOut.Trigger()};YAHOO.util.Event.addListener(this.m_domNode,"mouseover",onMouseOverFunc);YAHOO.util.Event.addListener(this.m_domNode,"mouseout",
onMouseOutFunc);if(this.GetMode()==D2L.DragDrop.Modes.Draggable||this.GetMode()==D2L.DragDrop.Modes.DraggableDroppable){this.m_yuiDDObject.onMouseDown=function(e){me.OnMouseDown.Trigger()};this.m_yuiDDObject.startDrag=function(x,y){me.SetIsGhostMovedToCursor(true);if(me.m_customGhostRenderer){me.m_customGhostControl=me.m_customGhostRenderer.call(me,me);var customGhostDom;if(D2L.Util.IsD2LControl(me.m_customGhostControl)){me.m_customGhostControl.BuildDom();customGhostDom=me.m_customGhostControl.GetDomNode()}else customGhostDom=
me.m_customGhostControl;me.m_ghost=UI.CreateElement("div");me.m_ghost=customGhostDom}else me.m_ghost=me.m_domNode.cloneNode(true);customProxy.style.height="auto";customProxy.style.width="auto";me.m_ghost.id="";me.m_ghost.style.margin="";if(UI.GetBrowserInfo().Type==D2L.UI.BrowserType.IE)me.m_ghost.style.styleFloat="";else me.m_ghost.style.cssFloat="";me.m_ghost.style.listStyleType="none";YAHOO.util.Dom.setStyle(me.m_ghost,"opacity",me.m_ghostOpacity);customProxy.appendChild(me.m_ghost);customProxy.style.cursor=
me.m_cursorDrag;me.m_ghost.style.cursor=me.m_cursorDrag;me.OnStartDrag.Trigger()};this.m_yuiDDObject.endDrag=function(e){var HideProxy=function(){customProxy.innerHTML="";customProxy.style.visibility="hidden";customProxy.style.height="0px";customProxy.style.width="0px"};customProxy.style.visibility="visible";var startPos=YAHOO.util.Dom.getXY(me.m_yuiDDObject.getEl());var anim=new YAHOO.util.Motion(me.m_yuiDDObject.getDragEl(),{points:{to:startPos}},0.25,YAHOO.util.Easing.easeOut);anim.onComplete.subscribe(function(){HideProxy()});
if(!me.m_isValid)anim.animate();else HideProxy();me.OnEndDrag.Trigger()};this.m_yuiDDObject.onInvalidDrop=function(e){me.m_isValid=false;me.m_ghost.style.paddingTop="0px";me.m_ghost.style.paddingLeft="0px"}}this.m_yuiDDObject.onDragOver=function(e,id){var dd=D2L.DragDrop.GetManager().GetDragDrop(id);if(dd.GetMode()==D2L.DragDrop.Modes.Droppable||dd.GetMode()==D2L.DragDrop.Modes.DraggableDroppable)if(me.m_isValid){me.OnOver.Trigger(dd,e);dd.OnDragOver.Trigger(me,e)}};var lastEnteredDD=null;this.m_yuiDDObject.onDragEnter=
function(e,id){var dd=D2L.DragDrop.GetManager().GetDragDrop(id);lastEnteredDD=dd;if(dd.GetMode()==D2L.DragDrop.Modes.Droppable||dd.GetMode()==D2L.DragDrop.Modes.DraggableDroppable)if(dd.IsInteractionValid(me,true)&&me.IsInteractionValid(dd,false)){me.m_ghost.style.cursor=me.m_cursorDrag;me.m_isValid=true;me.OnEnter.Trigger(dd);dd.OnDragEnter.Trigger(me)}else{me.m_isValid=false;me.m_ghost.style.cursor=me.m_cursorInvalid}};this.m_yuiDDObject.onDragOut=function(e,id){var dd=D2L.DragDrop.GetManager().GetDragDrop(id);
if(dd.GetMode()==D2L.DragDrop.Modes.Droppable||dd.GetMode()==D2L.DragDrop.Modes.DraggableDroppable){me.m_ghost.style.cursor=me.m_cursorDrag;if(lastEnteredDD==dd)me.m_isValid=false;me.OnExit.Trigger(dd);dd.OnDragExit.Trigger(me)}};this.m_yuiDDObject.onDragDrop=function(e,id){var dd=D2L.DragDrop.GetManager().GetDragDrop(id);if(dd.GetMode()==D2L.DragDrop.Modes.Droppable||dd.GetMode()==D2L.DragDrop.Modes.DraggableDroppable)if(me.m_isValid){me.OnDrop.Trigger(dd);dd.OnDragDropped.Trigger(me)}}},IsInteractionValid:function(dd,
isOver){if(this.m_customInteractionValidatorHandler!=null)return this.m_customInteractionValidatorHandler(dd,isOver);else return true},RemoveFromGroup:function(group){this.m_yuiDDObject.removeFromGroup(group)},SetCustomGhostRenderer:function(func){this.m_customGhostRenderer=func},SetIsGhostMovedToCursor:function(isMoved){if(this.m_yuiDDObject){var m=D2L.DragDrop.GetManager();if(isMoved){m.GetCustomProxy().style.paddingLeft="40px";m.GetCustomProxy().style.paddingTop="40px";if(this.m_yuiDDObject.setDelta)this.m_yuiDDObject.setDelta(25,
25);this.m_yuiDDObject.centerFrame=true;this.m_yuiDDObject.resizeFrame=false}else{this.m_yuiDDObject.centerFrame=false;this.m_yuiDDObject.resizeFrame=true;if(this.m_yuiDDObject.setDelta)this.m_yuiDDObject.setDelta(0,0);m.GetCustomProxy().style.paddingLeft="0px";m.GetCustomProxy().style.paddingTop="0px";m.GetCustomProxy().style.backgroundImage=""}}},SetCustomInteractionValidatorHandler:function(func){this.m_customInteractionValidatorHandler=func},SetHandle:function(control){var domNode=null;if(D2L.Util.IsD2LControl(control))domNode=
control.GetDomNode();else domNode=control;if(domNode.id=="")domNode.id=UI.GetUniqueHtmlId();this.m_yuiDDObject.setHandleElId(domNode.id)},SetData:function(key,value){this.m_data.Add(key,value)},SetGhostOpacity:function(opacity){this.m_ghostOpacity=opacity},SetScroll:function(scroll){this.m_scroll=scroll;this.m_yuiDDObject.scroll=scroll}});
D2L.DragDrop.Draggable=D2L.DragDrop.DraggableDroppable.extend({Construct:function(control,domNode,group){arguments.callee.$.Construct.call(this,control,domNode,group,D2L.DragDrop.Modes.Draggable)}});D2L.DragDrop.Droppable=D2L.DragDrop.DraggableDroppable.extend({Construct:function(control,domNode,group){arguments.callee.$.Construct.call(this,control,domNode,group,D2L.DragDrop.Modes.Droppable)}});if(window["D2L"]!==undefined&&D2L.LP.Web.Packaging!==undefined)D2L.LP.Web.Packaging.Register("D2L.LP.Web.Controls.DragDrop.default");
