
D2L.Control.SplitLayout=D2L.Control.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_height=null;this.m_isFullScreen=false;this.m_nestedSplitLayouts=[];this.m_orientation=D2L.Control.SplitLayout.Orientation.Horizontal;this.m_panels=[];this.m_recentlyResizedPanel=null;this.m_width=null},IntegrateControlMin:function(deserializer){arguments.callee.$.IntegrateControlMin.call(this,deserializer);this.m_height=deserializer.GetMember();this.m_width=deserializer.GetMember();this.m_isFullScreen=
deserializer.GetBoolean();this.m_orientation=deserializer.GetMember();this.m_panels=deserializer.GetObjectArrayMin(D2L.Control.SplitLayoutPanel);this.m_hasParentSplitLayout=deserializer.GetBoolean();if(this.m_hasParentSplitLayout){var parentSplitLayoutControlId=deserializer.GetObjectMin(D2L.Control.Id);if(parentSplitLayoutControlId)UI.GetControl(parentSplitLayoutControlId.ID(),parentSplitLayoutControlId.SID()).RegisterNestedSplitLayout(this)}var j=0;for(var i=0;i<this.m_panels.length;i++){if(this.GetDomNode().childNodes[j].tagName.toLowerCase().indexOf("h")==
0)j++;this.m_panels[i].IntegrateChild(this,this.GetDomNode().childNodes[j]);j++}this.InstallEvents();if(this.m_isFullScreen){UI.GetById("d2l_body").style.overflow="hidden";this.GetWindow().document.getElementsByTagName("html")[0].style.overflow="hidden"}var me=this;setTimeout(function(){me.AdjustSize();var loading=UI.GetById(me.GetMappedId()+"_loading");if(loading)loading.parentNode.removeChild(loading);me.GetDomNode().style.visibility="visible"},0)},AdjustHeight:function(){if(this.m_isFullScreen){var offsetParent=
this.GetDomNode();var posX=0;while(offsetParent){posX+=offsetParent.offsetTop;offsetParent=offsetParent.offsetParent}var windowHeight=UI.GetWindowHeight();var h=windowHeight-posX;if(h<10)h=10;var footer=D2L.Util.Dom.GetElementsByClassName(this.GetWindow().document,"d2l-dialog-footer");if(footer!=null&&footer.length>0)h-=footer[0].offsetHeight;this.GetDomNode().style.height=h+"px"}else if(this.m_height!="")this.GetDomNode().style.height=this.m_height+"px";else{if(this.m_hasParentSplitLayout)this.GetDomNode().style.height=
"100%";else this.GetDomNode().style.height="auto";this.GetDomNode().style.height=this.GetDomNode().offsetHeight+"px"}},AdjustSize:function(){this.AdjustHeight();this.AdjustWidth();this.AdjustPanels();for(var i=0;i<this.m_nestedSplitLayouts.length;i++)this.m_nestedSplitLayouts[i].AdjustSize()},AdjustWidth:function(){if(this.m_isFullScreen){this.GetDomNode().style.width="auto";this.GetDomNode().style.width=this.GetDomNode().offsetWidth+"px"}else if(this.m_width!="")this.GetDomNode().style.width=this.m_width+
"px";else{this.GetDomNode().style.width="auto";this.GetDomNode().style.width=this.GetDomNode().offsetWidth+"px"}},AdjustPanels:function(){var offsetProperty="";var styleProperty="";if(this.m_orientation==D2L.Control.SplitLayout.Orientation.Horizontal){offsetProperty="offsetWidth";styleProperty="width"}else{offsetProperty="offsetHeight";styleProperty="height"}var remainingSize=this.GetDomNode()[offsetProperty];var origSize=this.GetDomNode()[offsetProperty];var totalSize=0;var autoPanels=[];var autoPanelsAssignedSizes=
[];for(var i=0;i<this.m_panels.length;i++){var panel=this.m_panels[i];if(panel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Auto){panel.RemoveFixedSize(styleProperty);var size=panel.GetDomNode()[offsetProperty]+1;if(totalSize+size>origSize)size=origSize-totalSize;if(totalSize>=origSize)size=0;autoPanels.push(panel);autoPanelsAssignedSizes.push(size);panel.SetFixedSize(styleProperty,size);remainingSize-=size;totalSize+=size}}var pixelPanels=[];var pixelPanelsAssignedSizes=[];for(var i=0;i<
this.m_panels.length;i++){var panel=this.m_panels[i];if(panel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Pixel){var size=panel.GetSize().GetValue();if(totalSize+size>origSize)size=origSize-totalSize;if(totalSize>=origSize)size=0;pixelPanels.push(panel);pixelPanelsAssignedSizes.push(size);panel.SetFixedSize(styleProperty,size);remainingSize-=size;totalSize+=size}}var percentPanels=[];var percentPanelsAssignedSizes=[];var remainingSizeForPercent=remainingSize;for(var i=0;i<this.m_panels.length;i++){var panel=
this.m_panels[i];if(panel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Percentage){var size=Math.floor(remainingSizeForPercent*panel.GetSize().GetValue()/100);if(remainingSize<=0)size=0;if(totalSize+size>origSize)size=origSize-totalSize;if(totalSize>=origSize)size=0;percentPanels.push(panel);percentPanelsAssignedSizes.push(size);panel.SetFixedSize(styleProperty,size);remainingSize-=size;totalSize+=size}}var sumWildcardMultipliers=0;var remainingSizeForWildcard=remainingSize;for(var i=0;i<
this.m_panels.length;i++){var panel=this.m_panels[i];if(panel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Wildcard)sumWildcardMultipliers+=panel.GetSize().GetValue()}var eachWildcardSize=Math.floor(remainingSizeForWildcard/sumWildcardMultipliers);if(eachWildcardSize<0)eachWildcardSize=0;for(var i=0;i<this.m_panels.length;i++){var panel=this.m_panels[i];if(panel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Wildcard){panel.SetFixedSize(styleProperty,eachWildcardSize*panel.GetSize().GetValue());
remainingSize-=size;totalSize+=eachWildcardSize}}var forgiveness=this.m_panels.length;if(totalSize<origSize-forgiveness){var delta=origSize-totalSize;if(percentPanels.length>0){var sizeForEach=Math.floor(delta/percentPanels.length);for(var i=0;i<percentPanels.length;i++){var panel=percentPanels[i];panel.SetFixedSize(styleProperty,percentPanelsAssignedSizes[i]+sizeForEach)}}else if(pixelPanels.length>1||this.m_recentlyResizedPanel==null&&pixelPanels.length>0){var sizeForEach=Math.floor(delta/(this.m_recentlyResizedPanel==
null?pixelPanels.length:pixelPanels.length-1));for(var i=0;i<pixelPanels.length;i++){var panel=pixelPanels[i];if(panel!=this.m_recentlyResizedPanel)panel.SetFixedSize(styleProperty,pixelPanelsAssignedSizes[i]+sizeForEach)}}else if(autoPanels.length>1){var sizeForEach=Math.floor(delta/autoPanels.length);for(var i=0;i<autoPanels.length;i++){var panel=autoPanels[i];panel.SetFixedSize(styleProperty,autoPanelsAssignedSizes[i]+sizeForEach)}}}},GetOrientation:function(){return this.m_orientation},GetPanels:function(){return this.m_panels},
GetPanelByKey:function(key){var panels=this.GetPanels();for(var i=0;i<panels.length;i++)if(panels[i].GetKey()==key)return panels[i]},HandleBrowserResize:function(){if(this.m_isFullScreen||!this.m_width&&UI.IsPageFullScreen())this.AdjustSize()},HandlePanelResize:function(){this.AdjustSize()},InstallEvents:function(){var me=this;UI.GetWindowEventManager().Resize.Register(this,"HandleBrowserResize");for(var i=0;i<this.m_panels.length;i++){var panel=this.m_panels[i];panel.OnResize.Register(this,"HandlePanelResize")}if(this.m_isFullScreen)UI.GetMessageArea().OnHeightChange.RegisterMethod(function(){me.AdjustSize()})},
RegisterNestedSplitLayout:function(splitLayout){this.m_nestedSplitLayouts.push(splitLayout)}});D2L.Control.SplitLayout.Orientation={Horizontal:1,Vertical:2};
D2L.Control.SplitLayoutPanel=D2L.Control.extend({Construct:function(){arguments.callee.$.Construct.call(this);this.m_dragDropScrollTargetTop=null;this.m_dragDropScrollTargetBottom=null;this.m_hasParentSplitLayout=false;this.m_hasDragDropScrollTarget=false;this.m_backgroundColour="";this.m_beforeHiddingSize=null;this.m_gutterNode=null;this.m_hasGutter=true;this.m_isHidden=false;this.m_isResizable=true;this.m_isScrollable=true;this.m_key="";this.m_panelWrapper=null;this.m_panelWrapperInner=null;this.m_size=
null;this.m_splitLayout=null;this.m_title=null;this.OnResize=new D2L.EventHandler},DeserializeMin:function(deserializer){this.m_hasDragDropScrollTarget=deserializer.GetBoolean();this.m_backgroundColour=deserializer.GetMember();this.m_isResizable=deserializer.GetBoolean();this.m_hasGutter=deserializer.GetBoolean();this.m_isScrollable=deserializer.GetBoolean();this.m_title=deserializer.GetObjectMin(D2L.LP.Text.IText);this.m_size=D2L.Style.Utility.ParseMeasurementUnit(deserializer.GetMember());this.m_key=
deserializer.GetMember()},GetBackgroundColour:function(){return this.m_backgroundColour},GetIsHidden:function(){return this.m_isHidden},GetIsResizable:function(){return this.m_isResizable},GetIsScrollable:function(){return this.m_isScrollable},GetKey:function(){return this.m_key},GetNextSiblingPanel:function(){var nextPanel=null;for(var i=0;i<this.GetSplitLayout().GetPanels().length;i++){var panel=this.GetSplitLayout().GetPanels()[i];if(panel==this&&i+1<this.GetSplitLayout().GetPanels().length){nextPanel=
this.GetSplitLayout().GetPanels()[i+1];break}}return nextPanel},GetPreviousSiblingPanel:function(){var nextPanel=null;for(var i=0;i<this.GetSplitLayout().GetPanels().length;i++){var panel=this.GetSplitLayout().GetPanels()[i];if(panel==this&&i>1){nextPanel=this.GetSplitLayout().GetPanels()[i-1];break}}return nextPanel},GetTitle:function(){return this.m_title},GetSize:function(){return this.m_size},GetSplitLayout:function(){return this.m_splitLayout},HandleOnTransform:function(){this.OnResize.Trigger()},
HasGutter:function(){return this.m_hasGutter},Hide:function(){if(!this.m_isHidden){this.m_beforeHiddingSize=this.GetSize();var sizeZero=new D2L.Style.Measurement.Unit(D2L.Style.Measurement.UnitType.Px,0);this.SetSize(sizeZero);this.GetDomNode().style.display="none";this.m_isHidden=true}},IntegrateChild:function(parent,domNode){arguments.callee.$.IntegrateChild.call(this,parent,domNode);this.m_splitLayout=parent;if(this.HasGutter())this.m_gutterNode=this.GetDomNode().childNodes[1];if(this.m_hasDragDropScrollTarget)this.m_panelWrapper=
this.GetDomNode().firstChild.childNodes[1];else this.m_panelWrapper=this.GetDomNode().firstChild.firstChild;this.m_panelWrapperInner=this.m_panelWrapper.firstChild;if(this.m_hasDragDropScrollTarget){this.m_dragDropScrollTargetTop=this.GetDomNode().firstChild.firstChild;this.m_dragDropScrollTargetBottom=this.GetDomNode().firstChild.lastChild}this.InstallEvents()},InstallEvents:function(){var me=this;if(this.m_size.GetUnitType()==D2L.Style.Measurement.UnitType.Auto){if(this.GetDomNode().ID2LOnTransform===
undefined)UI.AttachObject(this.GetDomNode(),"ID2LOnTransform",new D2L.EventHandler);var me=this;this.GetDomNode().ID2LOnTransform.RegisterMethod(function(evt){me.HandleOnTransform()})}if(this.HasGutter()&&this.GetIsResizable())this.InstallResizeBarEvents();if(this.m_hasDragDropScrollTarget&&this.m_dragDropScrollTargetTop&&this.m_dragDropScrollTargetBottom){var dragDropScrollTargetTopDD=new D2L.DragDrop.Droppable(this.m_dragDropScrollTargetTop);var dragDropScrollTargetBottomDD=new D2L.DragDrop.Droppable(this.m_dragDropScrollTargetBottom);
var keepScrolling=true;var DoScroll=function(up){var DoScrollTimeOut=function(){DoScroll(up)};if(keepScrolling){if(up)me.m_panelWrapper.scrollTop=me.m_panelWrapper.scrollTop-10;else me.m_panelWrapper.scrollTop=me.m_panelWrapper.scrollTop+10;setTimeout(DoScrollTimeOut,10)}else clearTimeout(DoScrollTimeOut)};var StartScrolling=function(up){if(up)me.m_dragDropScrollTargetTop.className="dsl_p_m_sclUpHov";else me.m_dragDropScrollTargetBottom.className="dsl_p_m_sclDnwHov";keepScrolling=true;DoScroll(up);
D2L.DragDrop.GetManager().RefreshCache()};var StopScrolling=function(){me.m_dragDropScrollTargetTop.className="dsl_p_m_sclUp";me.m_dragDropScrollTargetBottom.className="dsl_p_m_sclDnw";keepScrolling=false;D2L.DragDrop.GetManager().RefreshCache()};dragDropScrollTargetTopDD.OnDragEnter.RegisterMethod(function(){StartScrolling(true)});dragDropScrollTargetBottomDD.OnDragEnter.RegisterMethod(function(){StartScrolling(false)});dragDropScrollTargetTopDD.OnDragExit.RegisterMethod(function(){StopScrolling()});
dragDropScrollTargetBottomDD.OnDragExit.RegisterMethod(function(){StopScrolling()});dragDropScrollTargetTopDD.OnDragDropped.RegisterMethod(function(){StopScrolling()});dragDropScrollTargetBottomDD.OnDragDropped.RegisterMethod(function(){StopScrolling()})}},InstallResizeBarEvents:function(){var me=this;if(this.GetSplitLayout().GetOrientation()==D2L.Control.SplitLayout.Orientation.Horizontal)this.m_gutterNode.style.cursor="e-resize";else this.m_gutterNode.style.cursor="n-resize";var HandleMouseDownEvent=
function(evt1){var gutterNodeClone=me.m_gutterNode.cloneNode(true);gutterNodeClone.style.position="absolute";gutterNodeClone.style.left="1000";gutterNodeClone.style.zIndex=UI.GetZIndex();YAHOO.util.Dom.setStyle(gutterNodeClone,"opacity",0.7);if(me.m_splitLayout.GetOrientation()==D2L.Control.SplitLayout.Orientation.Horizontal)gutterNodeClone.style.height=me.m_gutterNode.offsetHeight+"px";else gutterNodeClone.style.width=me.m_gutterNode.offsetWidth+"px";var d2lBody=UI.GetById("d2l_body");d2lBody.appendChild(gutterNodeClone);
var xy=YAHOO.util.Dom.getXY(me.m_gutterNode);var origXY=YAHOO.util.Dom.getXY(me.m_gutterNode);YAHOO.util.Dom.setXY(gutterNodeClone,xy);var theW=me.GetWindow();var parentLayoutXY=YAHOO.util.Dom.getXY(me.GetSplitLayout().GetDomNode());var parentLayoutHeight=me.GetSplitLayout().GetDomNode().offsetHeight;var parentLayoutWidth=me.GetSplitLayout().GetDomNode().offsetWidth;var prevSibilingPanel=me.GetPreviousSiblingPanel();var nexSiblingPanel=me.GetNextSiblingPanel();var bLeft;var bRight;var bTop;var bBottom;
if(me.GetSplitLayout().GetOrientation()==D2L.Control.SplitLayout.Orientation.Horizontal){if(prevSibilingPanel!=null)bLeft=YAHOO.util.Dom.getXY(prevSibilingPanel.GetDomNode())[0]+prevSibilingPanel.GetDomNode().offsetWidth;else bLeft=YAHOO.util.Dom.getXY(me.GetDomNode())[0];if(nexSiblingPanel)bRight=YAHOO.util.Dom.getXY(nexSiblingPanel.GetDomNode())[0]+nexSiblingPanel.GetDomNode().offsetWidth;else bRight=YAHOO.util.Dom.getXY(me.GetDomNode())[0]+me.GetDomNode().offsetWidth}else{if(prevSibilingPanel!=
null)bTop=YAHOO.util.Dom.getXY(prevSibilingPanel.GetDomNode())[1]+prevSibilingPanel.GetDomNode().offsetHeight;else bTop=YAHOO.util.Dom.getXY(me.GetDomNode())[1];if(nexSiblingPanel)bBottom=YAHOO.util.Dom.getXY(nexSiblingPanel.GetDomNode())[1]+nexSiblingPanel.GetDomNode().offsetHeight;else bBottom=YAHOO.util.Dom.getXY(me.GetDomNode())[1]+me.GetDomNode().offsetHeight}var panelShim=UI.GetShimController().AddShim(theW,me.IDomNode,false,true);var start=function(evt2){var newX=UI.GetCursorX(theW,evt2);var newY=
UI.GetCursorY(theW,evt2);var isOutOfBound=false;if(me.GetSplitLayout().GetOrientation()==D2L.Control.SplitLayout.Orientation.Horizontal){var xToSet=newX-gutterNodeClone.offsetWidth/2;if(xToSet<bLeft+5||xToSet>bRight-5-gutterNodeClone.offsetWidth)isOutOfBound=true;else{xy[0]=xToSet;d2lBody.style.cursor="e-resize"}}else{var yToSet=newY-gutterNodeClone.offsetHeight/2;if(yToSet<bTop+5||yToSet>bBottom-10-gutterNodeClone.offsetHeight)isOutOfBound=true;else{xy[1]=yToSet;d2lBody.style.cursor="n-resize"}}if(!isOutOfBound){gutterNodeClone.style.display=
"none";gutterNodeClone.style.display="block";YAHOO.util.Dom.setXY(gutterNodeClone,xy)}if(theW.event){theW.event.cancelBubble=true;theW.event.returnValue=false}else evt2.preventDefault()};var stop=function(){panelShim.SetIsVisible(false);d2lBody.style.cursor="default";var delta;if(me.GetSplitLayout().GetOrientation()==D2L.Control.SplitLayout.Orientation.Horizontal)delta=xy[0]-origXY[0];else delta=xy[1]-origXY[1];var thisPanel=me;var nextPanel=me.GetNextSiblingPanel();var panelToResize;if(thisPanel.GetSize().GetUnitType()==
D2L.Style.Measurement.UnitType.Pixel)panelToResize=thisPanel;else if(nextPanel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Pixel)panelToResize=nextPanel;else if(thisPanel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Auto)panelToResize=thisPanel;else if(nextPanel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Auto)panelToResize=nextPanel;else if(thisPanel.GetSize().GetUnitType()==D2L.Style.Measurement.UnitType.Percentage)panelToResize=thisPanel;else if(nextPanel.GetSize().GetUnitType()==
D2L.Style.Measurement.UnitType.Percentage)panelToResize=nextPanel;else panelToResize=thisPanel;if(panelToResize==nextPanel)delta=delta*-1;panelToResize.ResizeBy(delta);if(theW.document.detachEvent){theW.document.detachEvent("onmousemove",start);theW.document.detachEvent("onmouseup",stop)}else if(theW.document.removeEventListener){theW.document.removeEventListener("mousemove",start,true);theW.document.removeEventListener("mouseup",stop,true)}d2lBody.removeChild(gutterNodeClone)};if(theW.document.attachEvent){theW.document.attachEvent("onmousemove",
start);theW.document.attachEvent("onmouseup",stop)}else if(theW.document.addEventListener){theW.document.addEventListener("mousemove",start,true);theW.document.addEventListener("mouseup",stop,true)}};this.AttachObject(this.m_gutterNode,"onmousedown",function(evt){WindowEventManager.Click.Trigger(evt);HandleMouseDownEvent(evt)})},RemoveFixedSize:function(widthHeight){this.GetDomNode().style[widthHeight]="auto";this.m_panelWrapper.style[widthHeight]="auto";this.m_panelWrapperInner.style.width="auto";
this.m_panelWrapperInner.style.height="auto"},ResizeBy:function(pixelDelta){var currentSizePx;if(this.GetSplitLayout().GetOrientation()==D2L.Control.SplitLayout.Orientation.Horizontal)currentSizePx=this.GetDomNode().offsetWidth;else currentSizePx=this.GetDomNode().offsetHeight;var newSizePx=currentSizePx+pixelDelta;var newSize=new D2L.Style.Measurement.Unit(D2L.Style.Measurement.UnitType.Px,newSizePx);this.GetSplitLayout().m_recentlyResizedPanel=this;this.SetSize(newSize)},SetFixedSize:function(widthHeight,
size){this.GetDomNode().style[widthHeight]=size+"px";if(this.m_hasDragDropScrollTarget){this.m_panelWrapper.style.height="100%";this.m_dragDropScrollTargetBottom.style.width="100%";this.m_dragDropScrollTargetTop.style.width="100%"}var childSize=size;if(this.HasGutter())if(this.m_gutterNode.style.display!="none"){this.m_gutterNode.style.display="none";this.m_gutterNode.style.display="block";if(widthHeight=="width")childSize-=this.m_gutterNode.offsetWidth;else childSize-=this.m_gutterNode.offsetHeight}if(childSize>
0)this.m_panelWrapper.style[widthHeight]=childSize+"px";var scrollbarWidth=23;if(this.GetIsScrollable()){var widthSize=this.m_panelWrapper.offsetWidth-scrollbarWidth;if(widthSize>scrollbarWidth)this.m_panelWrapperInner.style.width=widthSize+"px";var heightSize=this.m_panelWrapper.offsetHeight-scrollbarWidth;if(this.m_hasDragDropScrollTarget)heightSize-=20;if(heightSize>20)this.m_panelWrapperInner.style.height=heightSize+"px"}else{this.m_panelWrapperInner.style.height="100%";this.m_panelWrapperInner.style.width=
"100%"}if(this.m_hasDragDropScrollTarget){var offHeight=this.m_panelWrapper.offsetHeight-20;if(offHeight>0)this.m_panelWrapper.style.height=offHeight+"px";var topWidth=this.m_panelWrapper.offsetWidth;if(topWidth>0)this.m_dragDropScrollTargetTop.style.width=topWidth-1+"px";var bottomWidth=this.m_panelWrapper.offsetWidth;if(bottomWidth>0)this.m_dragDropScrollTargetBottom.style.width=bottomWidth-1+"px"}},SetSize:function(size){this.m_size=size;this.OnResize.Trigger()},Show:function(){if(this.m_isHidden){this.GetDomNode().style.display=
"block";this.SetSize(this.m_beforeHiddingSize);this.m_isHidden=false}}});if(window["D2L"]!==undefined&&D2L.LP.Web.Packaging!==undefined)D2L.LP.Web.Packaging.Register("D2L.LP.Web.Controls.SplitLayout.default");